create table AUDIO_CLIPS (
    ID IDENTITY PRIMARY KEY,
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP NOT NULL,
    AUDIO_BYTES_FILE VARCHAR(200)
);

create index AUDIO_CLIPS_N1 on AUDIO_CLIPS(START_TIME);
